# Generated by Django 6.0.6 on 2026-06-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='Status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
