# Generated by Django 6.0.6 on 2026-06-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('carid', models.IntegerField()),
                ('Car_Photo', models.CharField(max_length=255)),
                ('Car_Name', models.CharField(max_length=100)),
                ('Price_Per_Day', models.IntegerField()),
                ('Car_Model', models.CharField(max_length=100)),
                ('Car_Number', models.CharField(max_length=100)),
                ('Fuel_Type', models.CharField(max_length=100)),
                ('Seating_Capacity', models.IntegerField()),
                ('Added_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=100)),
                ('Car_Name', models.CharField(max_length=100)),
                ('Car_Number', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('driver_license', models.CharField(max_length=100)),
                ('deicer_license_Photo', models.ImageField(upload_to='cars/')),
                ('Pickup_Date', models.DateField()),
                ('Pickup_Time', models.TimeField()),
                ('Return_Date', models.DateField()),
                ('Return_Time', models.TimeField()),
                ('Pickup_Location', models.CharField(max_length=100)),
                ('Drop_Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cardata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Car_Name', models.CharField(max_length=100)),
                ('Price_Per_Day', models.IntegerField()),
                ('Car_Model', models.CharField(max_length=100)),
                ('Car_Number', models.CharField(max_length=100)),
                ('Fuel_Type', models.CharField(max_length=100)),
                ('Transmissio', models.CharField(max_length=100)),
                ('Seating_Capacity', models.IntegerField()),
                ('Availability_Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='carphotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.IntegerField()),
                ('Car_Name', models.CharField(max_length=100)),
                ('Car_Photo', models.ImageField(upload_to='cars/')),
            ],
        ),
        migrations.CreateModel(
            name='logindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Payment_Method', models.CharField(max_length=50)),
                ('Payment_Status', models.CharField(default='Pending', max_length=50)),
                ('Transaction_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
